---
- name: Install Apache server
#    apt: name=apache2 update_cache=yes state=latest Alternative Approach
  apt: name={{packages}} update_cache=yes state=latest
  vars:
    packages:
      - apache2
      - curl
      - nano
#        - git=1.9.1-1ubuntu0.2
      - git
- name: Start Apache Service
  service: name=apache2 state=started
- name: Enable Apache Module re write
  apache2_module: name=rewrite state=present
  notify:
   - restart apache2
  #- name: ====== Install PHP =====================
  #  apt: name=php5 update_cache=yes version=
- name: ============ Create a index file from a template =================
  template: src=index.html dest=/var/www/html/index.html
  tags:
    - fileonly
